allowBuilds:
  automata-app: true
  automata-cache: true
  automata-db: true
  automata-rest: true
  automata-user-management: true
  automata-utils: true

  bcrypt: true
  better-sqlite3: true
  mongodb-memory-server: true
  unrs-resolver: true
  esbuild: true

# hmmm
blockExoticSubdeps: false

# local automata dev
# pnpm up to switch
# overrides:
#   automata-app: "file:./automata/automata-app"                #4
#   automata-cache: "file:./automata/automata-cache"            #1
#   automata-db: "file:./automata/automata-db"                  #1
#   automata-rest: "file:./automata/automata-rest"              #3
#   automata-user-management: "file:./automata/automata-user-management"  #2
#   automata-utils: "file:./automata/automata-utils"            #1

# revert
# overrides:
#   automata-app: "github:eamanola/automata-app"
#   automata-cache: "github:eamanola/automata-cache"
#   automata-db: "github:eamanola/automata-db"
#   automata-rest: "github:eamanola/automata-rest"
#   automata-user-management: "github:eamanola/automata-user-management"
#   automata-utils: "github:eamanola/automata-utils"
